stages:
    - build

build:
    before_script:
        - "which ssh-agent || ( apk update && apk add openssh )"
        - eval $(ssh-agent -s)
        - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
        - mkdir -p ~/.ssh
        - chmod 700 ~/.ssh
        - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
        - chmod 644 ~/.ssh/known_hosts
    tags:
        - novalab
    stage: build
    script:
        - ssh -o StrictHostKeyChecking=no ubuntu@34.203.170.11 "cd /var/www/html/delivery && git pull && php artisan migrate"
