version: '3'

services:
  nginx:
    image: nginx
    container_name: tmp_nginx
    ports:
      - "80:80"
    depends_on:
      - php
    volumes:
      - "../:/var/www/html"
      - "./nginx/conf.d/template.conf:/etc/nginx/conf.d/template.conf"

  php:
    build:
      context: ./php
    container_name: tmp_php
    volumes:
      - ../:/var/www/html
    environment:
      - "DBMS=${DBMS}"
      - "DB_PORT=${DB_PORT}"
      - "DB_NAME=${DB_NAME}"
      - "DB_USER=${DB_USER}"
      - "DB_PASSWORD=${DB_PASSWORD}"
    depends_on:
      - database

  database:
     image: mysql
     container_name: tmp_mysql
     ports:
       - "${DB_PORT}:3306"
     environment:
       - "MYSQL_DATABASE: root"
       - "MYSQL_ROOT_PASSWORD= root"
       - "MYSQL_TAGS=dev"
       - "MYSQL_NAME=mysql"
     volumes:
       - ./database:/var/lib/mysql
  adminer:
     image: adminer
     ports:
       - "8081:8080"

#  database:
#    image: mdillon/postgis
#    container_name: tmp_postgres
#    environment:
#      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
#      - "PGDATA=/var/lib/postgresql/data"
#      - "DB_NAME=${DB_NAME}"
#      - "DB_USER=${DB_USER}"
#      - "DB_PASSWORD=${DB_PASSWORD}"
#      - "TEST_DB_NAME=${TEST_DB_NAME}"
#      - "TEST_DB_USER=${TEST_DB_USER}"
#      - "TEST_DB_PASSWORD=${TEST_DB_PASSWORD}"
#    volumes:
#      - "./postgres/initdb.sh:/docker-entrypoint-initdb.d/z1.sh"
#      - "./postgres/initdb-test.sh:/docker-entrypoint-initdb.d/z2.sh:ro"
#      - "./database:/var/lib/postgresql/data"
#    #  for Windows (https://github.com/docker/for-win/issues/445)
#    #  - "postgres_database:/var/lib/postgresql/data"
#    ports:
#      - "${DB_PORT}:5432"

#  pgadmin:
#    container_name: tmp_pgadmin4
#    image: dpage/pgadmin4
#    depends_on:
#      - database
#    volumes:
#      - "./pgadmin_storage:/var/lib/pgadmin/storage"
#      - "./postgres/pgservers.json:/tmp/output_file.json"
#    environment:
#      - "PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}"
#      - "PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}"
#      - "PGADMIN_SERVER_JSON_FILE=/tmp/output_file.json"
#    ports:
#      - "${PGADMIN_PORT}:80"
#  # for Windows (https://github.com/docker/for-win/issues/445)


